namespace: pro-bigmac-index-back
replicaCount: 1
registry: harbor.server.local/danielbeltejar/bigmac-index
image:
  pullPolicy: IfNotPresent
service:
  type: ClusterIP
  port: 80
  targetPort: 8000
extraEnv:
- name: "TZ"
  value: "UTC"
- name: DB_HOST
  value: mariadb-service
- name: DB_PORT
  value: "3306"
- name: DB_DATABASE
  value: bigmac
- name: DB_USER
  value: bigmac
- name: DB_PASSWORD
  valueFrom:
    secretKeyRef:
      key: password
      name: bigmac-index-secret
extraEnvFrom: []
resources:
  requests:
    memory: "128Mi"
  limits:
    cpu: 250m
    memory: "256Mi"
